// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC41QcZIk2yiPJMmzXpFXZXT87-ksO1mhc',
    appId: '1:914933476469:web:f0170e94b6a93e28a09c3c',
    messagingSenderId: '914933476469',
    projectId: 'elearn-firebase-test',
    authDomain: 'elearn-firebase-test.firebaseapp.com',
    storageBucket: 'elearn-firebase-test.firebasestorage.app',
    measurementId: 'G-PM28C54EKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdIkU4xNhrSzjvir-HxccbCGh1OkOTbso',
    appId: '1:914933476469:android:06ef79c3cfcb78bea09c3c',
    messagingSenderId: '914933476469',
    projectId: 'elearn-firebase-test',
    storageBucket: 'elearn-firebase-test.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC41QcZIk2yiPJMmzXpFXZXT87-ksO1mhc',
    appId: '1:914933476469:web:eb626db91779a3dba09c3c',
    messagingSenderId: '914933476469',
    projectId: 'elearn-firebase-test',
    authDomain: 'elearn-firebase-test.firebaseapp.com',
    storageBucket: 'elearn-firebase-test.firebasestorage.app',
    measurementId: 'G-HV1B5T7ME3',
  );

}